version: '3.1'
services:
  web:
    image: 'mcr.microsoft.com/azure-sql-edge'
    ports:
      - '1433:1433'
    volumes:
      - 'C:\Users\myuser\mydata:/var/opt/mssql/data'
    networks:
      - finshark
    environment:
      USER: 'sa'
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'MyC0m9l&xP@ssw0rd'
      MSSQL_PID: 'Developer'


